name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - run: docker login -u ${{secrets.DOCKER_USERNAME}} - p ${{secrets.DOCKER_PASSWORD}}
    - run: docker build -t amasaabu/react-test -f ./client/Dockerfile.dev ./client
    - run: docker run -e CI=true amasaabu/react-test npm test
    
    - name: build for production
      run: docker build -t amasaabu/multi-client ./client
      run: docker build -t amasaabu/multi-nginx ./nginx
      run: docker build -t amasaabu/multi-server ./server
      run: docker build -t amasaabu/multi-worker ./worker

    - name: Generate deploymentt package
      run: zip -r deploy.zip . -x '*.git'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRETE_ACCESS_KEY}}
        application_name: Docker
        environment_name: Docker-env-1
        existing_bucket_name: elasticbeanstalk-us-east-1-451613728407
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
